import asyncio
import json
import os
import secrets
import uuid
from unittest import mock

import pytest
import yaml

from drools.dispatch import establish_async_channel, handle_async_messages
from drools.rule import Rule
from drools.ruleset import (
    Ruleset,
    action_info_exists,
    add_action_info,
    delete_action_info,
    disable_leader,
    enable_leader,
    get_action_info,
    get_ha_stats,
    initialize_ha,
)


def load_ast(filename: str) -> dict:
    test_dir = os.path.dirname(os.path.realpath(__file__))
    with open(f"{test_dir}/{filename}") as f:
        test_data = yaml.safe_load(f)
    return test_data


_SSL_CERTS_DIR = os.path.join(
    os.path.dirname(os.path.realpath(__file__)), "ssl-certs"
)


@pytest.fixture
def db_params():
    """DB connection parameters for PostgreSQL with SSL.

    Defaults point to tests/ssl-certs/ (generated by
    generate-certs.sh) and port 5433 (docker-compose-ssl.yaml).

    Override with environment variables if needed:
        POSTGRES_HOST, POSTGRES_PORT, POSTGRES_DB,
        POSTGRES_USER, POSTGRES_PASSWORD,
        POSTGRES_SSLMODE, POSTGRES_SSLROOTCERT,
        POSTGRES_SSLCERT, POSTGRES_SSLKEY, POSTGRES_SSLPASSWORD
    """
    return {
        "db_type": "postgres",
        "host": os.environ.get("POSTGRES_HOST", "localhost"),
        "port": int(os.environ.get("POSTGRES_PORT", "5433")),
        "database": os.environ.get("POSTGRES_DB", "eda_ha_db"),
        "user": os.environ.get("POSTGRES_USER", "eda_user"),
        "password": os.environ.get("POSTGRES_PASSWORD", secrets.token_hex(8)),
        "sslmode": os.environ.get("POSTGRES_SSLMODE", "verify-full"),
        "sslrootcert": os.environ.get(
            "POSTGRES_SSLROOTCERT",
            os.path.join(_SSL_CERTS_DIR, "ca.crt"),
        ),
        "sslcert": os.environ.get(
            "POSTGRES_SSLCERT",
            os.path.join(_SSL_CERTS_DIR, "client.crt"),
        ),
        "sslkey": os.environ.get(
            "POSTGRES_SSLKEY",
            os.path.join(_SSL_CERTS_DIR, "client.key"),
        ),
        "sslpassword": os.environ.get(
            "POSTGRES_SSLPASSWORD", secrets.token_hex(8)
        ),
    }


@pytest.mark.asyncio
async def test_ha_ssl_basic(db_params):
    """Test HA initialization and rule firing over SSL PostgreSQL."""

    # Skip if SSL certificates don't exist
    if not os.path.exists(db_params["sslcert"]) or not os.path.exists(
        db_params["sslkey"]
    ):
        pytest.skip(
            "SSL certificates not found. "
            "Run tests/ssl-certs/generate-certs.sh to generate them."
        )

    reader, writer = await establish_async_channel()
    async_task = asyncio.create_task(handle_async_messages(reader, writer))

    try:
        # 1. Initialize HA with SSL db_params
        instance_uuid = str(uuid.uuid4())
        initialize_ha(instance_uuid, "worker-ssl-1", db_params, {})

        # 2. Create a ruleset
        test_data = load_ast("asts/rules_with_assignment.yml")
        ruleset_data = test_data[0]["RuleSet"]

        captured_matches = []

        def capture_callback(matches):
            captured_matches.append(matches)
            async_task.cancel()

        my_callback = mock.Mock(side_effect=capture_callback)
        rs = Ruleset(
            name=ruleset_data["name"],
            serialized_ruleset=json.dumps(ruleset_data),
            ha_enabled=True,
        )
        rs.add_rule(Rule("assignment", my_callback))

        # 3. Enable leader
        enable_leader()

        ha_stats = get_ha_stats()
        print(f"HA Stats (SSL): {ha_stats}")
        assert ha_stats is not None
        assert isinstance(ha_stats, dict)

        # 4. Assert an event that fires the rule
        rs.assert_event(json.dumps({"i": 67}))

        await async_task

        # 5. Verify the rule fired
        assert my_callback.called
        assert len(captured_matches) > 0

        matching_uuid = captured_matches[0].matching_uuid
        assert matching_uuid is not None

        # 6. Verify action persistence over SSL
        action_data = json.dumps({"action": "print_event", "status": "1"})
        add_action_info(ruleset_data["name"], matching_uuid, 0, action_data)
        assert action_info_exists(ruleset_data["name"], matching_uuid, 0)
        retrieved = get_action_info(ruleset_data["name"], matching_uuid, 0)
        assert retrieved == action_data

        delete_action_info(ruleset_data["name"], matching_uuid)

        # 7. Clean up
        disable_leader()
        rs.end_session()
    finally:
        if not async_task.done():
            async_task.cancel()
            await async_task
